# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20180709_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(default=datetime.datetime(2018, 7, 9, 12, 27, 22, 788288, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
