# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180528_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
