# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180701_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='maincontent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcontent_a',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcontent_b',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcontent_c',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcontent_d',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcontent_e',
            field=models.TextField(blank=True),
        ),
    ]
