# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180702_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='maincontent',
            field=models.TextField(blank=True),
        ),
    ]
