# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180702_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcontent',
            field=models.TextField(blank=True),
        ),
    ]
