# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-02 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_subcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content123',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subcontent',
        ),
    ]
