# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180703_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User'},
        ),
    ]
