# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_bloggerprofile_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('newsletters', models.CharField(max_length=100)),
                ('rss', models.CharField(max_length=100)),
                ('privacy', models.CharField(max_length=100)),
            ],
        ),
    ]
