# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggerprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='newsletters',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='privacy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='rss',
            field=models.TextField(blank=True),
        ),
    ]
