# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20180704_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='FooterText',
        ),
    ]
