# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20180704_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertext',
            old_name='about',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='newsletters',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='rss',
        ),
        migrations.AddField(
            model_name='footertext',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
