# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20180704_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='footertext',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
