# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_footertext_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
