# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20180704_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='fb_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='linkdin_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='twitter_link',
            field=models.TextField(blank=True),
        ),
    ]
