# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20180705_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggerprofile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bloggerprofile',
            name='linkdin_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bloggerprofile',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
