# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20180705_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
