# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='maincontent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
