# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20180709_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
