# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20180709_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpictures',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='postpictures',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='postpictures',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='postpictures',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='postpictures',
            name='image5',
        ),
        migrations.AddField(
            model_name='postpictures',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpictures',
            name='image_1',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_pic, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='postpictures',
            name='image_2',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_pic, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='postpictures',
            name='image_3',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_pic, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='postpictures',
            name='image_4',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location_pic, width_field='width_field'),
        ),
    ]
