# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-22 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_auto_20180714_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location_photo),
        ),
    ]
