# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_auto_20180820_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/None/default.png', height_field='height_field', upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
