# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-09-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_auto_20180821_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='svg_class',
            field=models.TextField(blank=True, null=True),
        ),
    ]
