# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-09-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_auto_20230924_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(help_text='Max 300 char', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='For best view it should be 700 x 400 px.Should not be below 450 x 300', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(help_text='Max 500 char', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Max 130 char', max_length=130),
        ),
    ]
