# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2023-10-04 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_auto_20230929_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Max 300 char', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Max 130 char', max_length=300),
        ),
    ]
