

version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: infoboxhub
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ${PWD}:/app
      - ${PWD}/static_cdn:/app/static_cdn
      - ${PWD}/media_cdn:/app/media_cdn 
    ports:
      - 8000:8000
    restart: "on-failure"
    environment:
      - ENV=DEV

# volumes:
#   static_cdn:
#   media_cdn: 